on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run unit tests
      run: dotnet test --no-restore --filter FullyQualifiedName~tests

  tests-integration:
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: ${{ secrets.JARED_DB_PASSWORD }}
          ACCEPT_EULA: Y
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Initial Catalog=${{ secrets.JARED_TEST_DB_NAME }};User ID=${{ secrets.JARED_DB_USER }};Password=${{ secrets.JARED_DB_PASSWORD }};"
        run: dotnet test --no-restore --verbosity normal
