<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="$(JaredRoot)\tests.targets" />

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\app\Jared.Client\Jared.Client.csproj" />
    </ItemGroup>

</Project>