on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'  # Zmodyfikuj wed³ug wersji, której u¿ywasz
    
      - name: Restore dependencies
        run: dotnet restore
    
      - name: Run unit tests
        run: dotnet test --no-restore --filter 'FullyQualifiedName~tests'