<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(JaredRoot)\tests.targets" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\shared\Jared.Shared\Jared.Shared.csproj" />
    <ProjectReference Include="..\..\src\api\Jared.Domain\Jared.Domain.csproj" />
    <ProjectReference Include="..\..\src\api\Jared.Application\Jared.Application.csproj" />
    <ProjectReference Include="..\..\src\api\Jared.Infrastructure\Jared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\api\Jared.Presentation\Jared.Presentation.csproj" />
    <ProjectReference Include="..\..\src\app\Jared.Client\Jared.Client.csproj" />
    <ProjectReference Include="..\..\src\app\Jared.UI\Jared.UI.csproj" />
    <ProjectReference Include="..\..\src\Jared.Api\Jared.Api.csproj" />
    <ProjectReference Include="..\..\src\Jared.App\Jared.App.csproj" />
  </ItemGroup>

</Project>
